### ISSUE TITLE
Repository is template

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [silverstripe/silverstripe-module#14]
Hello!
There is a feature on GitHub that I want to make you aware of. It's called a "template repository." You can read more about it here: https://help.github.com/en/articles/creating-a-template-repository.

You should know that this repository is a template repository and should be marked as such. Currently, there are two ways to begin working on a SilverStripe module using the skeleton. The first is to "composer require" the package and make the modifications in the "vendor" folder.
The second is to fork the repository. Both this options are suboptimal because the repository created is linked back to this one. If people instead create their project as a GitHub Repository with this repository as a template, the repository is properly separated from this one, as module developers invariably prefer that it be separated. Thank you!

Stuart Simon

**Comment by robbieaverill** [comment]
Hi @ssimo3lsuhsc, thanks for pointing this out! It's a cool new feature of GitHub =) I've marked this repository as a template, so now you can create new projects from it without carrying over the VCS history. Thanks!
