### ISSUE TITLE
Suggestion: remove 'fonts' directory from rules/test

### ISSUE THREAD

**Issue by micschk** [silverstripe/silverstripe-module#34]
Currently font-files only get picked up if they're inside a `fonts/` directory. I'm not sure why the fonts directory is in the filter but it seems to me this might just as well be removed so referenced fonts files would get picked up from anywhere (eg including ones installed via npm/yarn)?

Eg remove the `fonts[\/\\]` or even the whole `fonts[\/\\]([\w_-]+)` part from the rule/test in `css/modules.js`:
```
    rules: [
      ...
      {
        test: /fonts[\/\\]([\w_-]+)\.(woff2?|eot|ttf|svg)$/,
        loader: 'file-loader',
        options: {
          name: 'fonts/[name].[ext]?h=[contenthash]',
        },
      },
    ],
...
```

**Comment by ChloeSartorelli** [comment]
`fonts[\/\\]` doesn't seem to appear anywhere in this repository(https://github.com/search?q=repo%3Asilverstripe%2Fsilverstripe-module%20fonts%5B%5C%2F%5C%5C%5D&type=code) so I'm going to close this under the assumption that we've removed whatever that's referring to. Feel free to add more information about where this is if it's still relevant.
