### ISSUE TITLE
Unable to resolve path to module 'lib/Injector'

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-module#35]
This template will not work out of the box.  
Building actually works (`NODE_ENV=production webpack -p --bail --progress`), but if you run the build task (`yarn && yarn lint && NODE_ENV=production webpack -p --bail --progress`) it will also lint, which throws the following errors:
```
$ eslint client/src

/vagrant/silverstripe/silverstripe-module/client/src/boot/registerComponents.js
  1:22  error  Unable to resolve path to module 'lib/Injector'  import/no-unresolved
  1:22  error  Missing file extension for "lib/Injector"        import/extensions

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by maxime-rainville** [comment]
Fixed by #37
