### ISSUE TITLE
yarn link error: import/no-extraneous-dependencies (silverstripe-admin)

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-module#38]
```
$ yarn lint
yarn run v1.22.11
$ eslint client/src && sass-lint client/src

.../www/vendor/silverstripe/silverstripe-module/client/src/boot/registerComponents.js
  1:1  error  'silverstripe-admin' should be listed in the project's dependencies. Run 'npm i -S silverstripe-admin' to add it  import/no-extraneous-dependencies

✖ 1 problem (1 error, 0 warnings)
```

We are including silverstripe-admin as an external on purpose to share the react instance. So we should probably add an exception to the linting for silverstripe-admin.

---

Or, given that we heavily rely on externals, should we perhaps completely disable this check?

**Comment by ssmarco** [comment]
It worked for me using @silverstripe/eslint-config 0.0.6 version

**Comment by ChloeSartorelli** [comment]
I'm going to assume based on the above comment and the lack of response that this is resolved.
