### ISSUE TITLE
Update with CMS 5 compatibility

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-module#40]
This module template reflects CMS 4 standards. We should update everything and anything necessary for this to be compatible with CMS 5 and reflect the latest best practices. That may just mean updating composer.json dependencies to make it clear this is still relevant, or it may involve more work than that.

The other issues in this repository are also relevant to this work.

## Acceptance criteria
- There's a new CMS5 branch for the repo
- Readme is updated to match CMS 5.
- CMS5 branch is the default branch
- CMS5 branch is updated to reflect current best practice.
- There's a dummy CI build set up.
- CMS4 branch is still usable.

## PRs
- https://github.com/silverstripe/silverstripe-module/pull/41

**Comment by maxime-rainville** [comment]
PR merged.
