### ISSUE TITLE
Incorrect Indentation (Spaces not Tabs)

### ISSUE THREAD

**Issue by gordonbanderson** [silverstripe/silverstripe-module#9]
In https://github.com/silverstripe/silverstripe-module/blob/master/.editorconfig the indentation style is set to spaces

```
indent_size = 4
indent_style = space
```

This appears to be at odds with the SilverStripe coding conventions https://docs.silverstripe.org/en/3.2/getting_started/coding_conventions/ which quite clearly states "Always use hard tabs rather then spaces for indentation, with one tab per nesting level."

**Comment by MichaelJJames** [comment]
Hi Gordon, 
I believe this might be something to do with the PSR-2 standards

**Comment by gordonbanderson** [comment]
I realise that now, having updated my modules.  Had forgotten I'd posted this :)

**Comment by tractorcow** [comment]
All core modules will move to psr-2 soonish too. :) I hope you hate tabs!

**Comment by gordonbanderson** [comment]
I'm easy either way on the spaces or tabs front, just as long as it's consistent...  Likes of .editorconfig does help.  I also came upon this yesterday which is quite interesting, using a git hook to force coding standards compliance https://dyrynda.com.au/blog/automatically-fixing-code-styles-before-you-commit-your-code
